exports.LOGIN_TYPE = {
  APPLE: 1,
  GOOGLE: 2,
  QUICK: 3,
  MOBILE: 4
};

exports.HOST_REQUEST_STATUS = {
  PENDING: 1,
  ACCEPTED: 2,
  DECLINED: 3,
};

exports.GIFTTYPE_TYPE = {
  IMAGE: 1,
  GIF: 2,
  SVGA: 3,
  MP4: 4,
  WEBP: 5,
};

exports.HISTORY_TYPE = {
  LOGINBONUS: 1,
  GIFT_IN_LIVE: 2,
  GIFT_IN_VIDEO_CALL: 3,
  WITHDRAW_BY_HOST: 5,
  DAILY_CHECK_IN_REWARD: 6,
  COIN_PLAN_PURCHASE: 7,
  VIP_PLAN_PURCHASE: 8,
  CHAT_WITH_HOST: 9,
  GIFT_IN_CHAT: 10,
  PRIVATE_AUDIO_CALL: 11,
  PRIVATE_VIDEO_CALL: 12,
  RANDOM_VIDEO_CALL: 13,
  ADMIN_ADD_COIN: 14,
  ADMIN_DEDUCT_COIN: 15,
  RESELLER_RECHARGE_USER: 16, // When reseller recharged user with coins
  LUCKY_SPIN_REWARD: 17,
  PK_BATTLE_GIFT: 18,
};

exports.COIN_TRANSACTION_TYPE = {
  ADD: 1,
  DEDUCT: 2,
};

exports.RECHARGE_STATUS = {
  PENDING: "pending",
  COMPLETED: "completed",
  FAILED: "failed",
  CANCELLED: "cancelled",
};

exports.MESSAGE_TYPE = {
  MESSAGE: 1,
  IMAGE: 2,
  AUDIO: 3,
  GIFT: 4,
  AUDIO_CALL: 5,
  VIDEO_CALL: 6,
};

exports.CALL_TYPE = {
  RECEIVED: 1,
  DECLINED: 2,
  MISCALLED: 3,
};

exports.WITHDRAWAL_STATUS = {
  DEFAULT: 0,
  PENDING: 1,
  ACCEPTED: 2,
  DECLINED: 3,
};

exports.WITHDRAWAL_PERSON = {
  AGENCY: 1,
  HOST: 2,
};

exports.NOTIFICATION_PERSON_TYPE = {
  CUSTOMER: 1,
  PROVIDER: 2,
  AGENCY: 3,
};
